name: push-urls-to-github
on:
  schedule:
    - cron: 0/2 * * * * 
  watch:
    types: started
jobs:
  push-urls-to-baidu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: push-urls-to-github
        run: |
          wget https://eonegh.com/usr/plugins/Handsome/cache/search.json -qO search.json
    
      - name: commit #上传新的refresh_token
        run: |
          git config --global user.email AutoupdateRobot@email.com
          git config --global user.name AutoupdateRobot
          git add .
          git commit -m "update new refresh_token" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TEST_TOKEN }}
